export const CHANGE_APP_PATH = 'CHANGE_APP_PATH';
export const CHANGE_LOADING = 'CHANGE_LOADING';

// SEARCH OPORTUNITIES
export const SEARCH_SKILLS_CHANGE = 'SEARCH_SKILLS_CHANGE';
export const SEARCH_SKILLS_CLEAR = 'SEARCH_SKILLS_CLEAR';
export const SKILLS_CLEAR = 'SKILLS_CLEAR';
export const SKILLS_ADD = 'SKILLS_ADD';
export const MYSKILL_ADD = 'MYSKILL_ADD';
export const MYSKYLL_REMOVE = 'MYSKYLL_REMOVE'; 
export const SEARCH_SKILLS_CLEAR_ALL = 'SEARCH_SKILLS_CLEAR_ALL';

// OPPORTUNITIES
export const ADD_OPPORTUNITIES = 'ADD_OPPORTUNITIES';
