export const CHANGE_APP_PATH = 'CHANGE_APP_PATH';
export const CHANGE_LOADING = 'CHANGE_LOADING';
export const SWITCH_SIGNIN= 'SWITCH_SIGNIN';
export const SWITCH_LOGIN='SWITCH_LOGIN';
export const LOGIN_FORM_EMAIL='LOGIN_FORM_EMAIL';
export const LOGIN_FORM_PASS='LOGIN_FORM_PASS';
export const SIGNIN_FORM_EMAIL='SIGNIN_FORM_EMAIL';
export const SIGNIN_FORM_PASS='SIGNIN_FORM_PASS';


// SEARCH OPORTUNITIES
export const SEARCH_SKILLS_CHANGE = 'SEARCH_SKILLS_CHANGE';
export const SEARCH_SKILLS_CLEAR = 'SEARCH_SKILLS_CLEAR';
export const SKILLS_CLEAR = 'SKILLS_CLEAR';
export const SKILLS_ADD = 'SKILLS_ADD';
export const MYSKILL_ADD = 'MYSKILL_ADD';
export const MYSKYLL_REMOVE = 'MYSKYLL_REMOVE'; 
export const SEARCH_SKILLS_CLEAR_ALL = 'SEARCH_SKILLS_CLEAR_ALL';

// OPPORTUNITIES
export const ADD_OPPORTUNITIES = 'ADD_OPPORTUNITIES';
